non-prod:
  outputs:
    dev:
      database: DbtTest
      driver: ODBC Driver 18 for SQL Server
      encrypt: false
      password: '{{ env_var("DB_PASSWORD") }}'
      port: 1433
      schema: dbt_test
      server: badvalue
      threads: 1
      trust_cert: true
      type: sqlserver
      user: sa
  target: dev
