worker:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: I1014
      port: 1433
      database: DbtTest
      schema: dbt_test
      user: billying
      password: Bill2380
      encrypt: False
      trust_cert: True